//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AnperoFrontend.AnperoService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AnperoServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AnperoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCommonConfigOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AnperoService() {
            this.Url = global::AnperoFrontend.Properties.Settings.Default.AnperoFrontend_AnperoService_AnperoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCommonConfigCompletedEventHandler GetCommonConfigCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCommonConfig", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Webconfig GetCommonConfig(int storeId, string tokenKey) {
            object[] results = this.Invoke("GetCommonConfig", new object[] {
                        storeId,
                        tokenKey});
            return ((Webconfig)(results[0]));
        }
        
        /// <remarks/>
        public void GetCommonConfigAsync(int storeId, string tokenKey) {
            this.GetCommonConfigAsync(storeId, tokenKey, null);
        }
        
        /// <remarks/>
        public void GetCommonConfigAsync(int storeId, string tokenKey, object userState) {
            if ((this.GetCommonConfigOperationCompleted == null)) {
                this.GetCommonConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCommonConfigOperationCompleted);
            }
            this.InvokeAsync("GetCommonConfig", new object[] {
                        storeId,
                        tokenKey}, this.GetCommonConfigOperationCompleted, userState);
        }
        
        private void OnGetCommonConfigOperationCompleted(object arg) {
            if ((this.GetCommonConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCommonConfigCompleted(this, new GetCommonConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Webconfig {
        
        private Menu[] menuListField;
        
        private string faceBookLinkField;
        
        private string skypeField;
        
        private string hotLineField;
        
        private string pageScriptField;
        
        private string footerField;
        
        private string logoField;
        
        private string descField;
        
        /// <remarks/>
        public Menu[] MenuList {
            get {
                return this.menuListField;
            }
            set {
                this.menuListField = value;
            }
        }
        
        /// <remarks/>
        public string FaceBookLink {
            get {
                return this.faceBookLinkField;
            }
            set {
                this.faceBookLinkField = value;
            }
        }
        
        /// <remarks/>
        public string Skype {
            get {
                return this.skypeField;
            }
            set {
                this.skypeField = value;
            }
        }
        
        /// <remarks/>
        public string HotLine {
            get {
                return this.hotLineField;
            }
            set {
                this.hotLineField = value;
            }
        }
        
        /// <remarks/>
        public string PageScript {
            get {
                return this.pageScriptField;
            }
            set {
                this.pageScriptField = value;
            }
        }
        
        /// <remarks/>
        public string Footer {
            get {
                return this.footerField;
            }
            set {
                this.footerField = value;
            }
        }
        
        /// <remarks/>
        public string Logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Menu {
        
        private Menu[] chidMenuField;
        
        private int idField;
        
        private string linkField;
        
        private int parentIdField;
        
        private int priotyField;
        
        private string tittleField;
        
        /// <remarks/>
        public Menu[] ChidMenu {
            get {
                return this.chidMenuField;
            }
            set {
                this.chidMenuField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public int ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        public int Prioty {
            get {
                return this.priotyField;
            }
            set {
                this.priotyField = value;
            }
        }
        
        /// <remarks/>
        public string Tittle {
            get {
                return this.tittleField;
            }
            set {
                this.tittleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetCommonConfigCompletedEventHandler(object sender, GetCommonConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCommonConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCommonConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Webconfig Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Webconfig)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591