//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AnperoFrontend.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AnperoServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AnperoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback addContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchArticleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArticleByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRandomAdsSlideOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAdsSlideOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCommonConfigOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBlogCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductByParentCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductByCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSaleProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductDetailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AnperoService() {
            this.Url = global::AnperoFrontend.Properties.Settings.Default.AnperoFrontend_AnperoService_AnperoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLocationCompletedEventHandler GetLocationCompleted;
        
        /// <remarks/>
        public event addContactCompletedEventHandler addContactCompleted;
        
        /// <remarks/>
        public event SearchArticleCompletedEventHandler SearchArticleCompleted;
        
        /// <remarks/>
        public event GetArticleByIdCompletedEventHandler GetArticleByIdCompleted;
        
        /// <remarks/>
        public event AddOrderCompletedEventHandler AddOrderCompleted;
        
        /// <remarks/>
        public event GetRandomAdsSlideCompletedEventHandler GetRandomAdsSlideCompleted;
        
        /// <remarks/>
        public event GetAdsSlideCompletedEventHandler GetAdsSlideCompleted;
        
        /// <remarks/>
        public event GetCommonConfigCompletedEventHandler GetCommonConfigCompleted;
        
        /// <remarks/>
        public event GetBlogCategoryCompletedEventHandler GetBlogCategoryCompleted;
        
        /// <remarks/>
        public event SearchProductCompletedEventHandler SearchProductCompleted;
        
        /// <remarks/>
        public event GetProductByParentCategoryCompletedEventHandler GetProductByParentCategoryCompleted;
        
        /// <remarks/>
        public event GetProductByCategoryCompletedEventHandler GetProductByCategoryCompleted;
        
        /// <remarks/>
        public event GetSaleProductCompletedEventHandler GetSaleProductCompleted;
        
        /// <remarks/>
        public event GetProductDetailCompletedEventHandler GetProductDetailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Location[] GetLocation(int ParentId) {
            object[] results = this.Invoke("GetLocation", new object[] {
                        ParentId});
            return ((Location[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLocationAsync(int ParentId) {
            this.GetLocationAsync(ParentId, null);
        }
        
        /// <remarks/>
        public void GetLocationAsync(int ParentId, object userState) {
            if ((this.GetLocationOperationCompleted == null)) {
                this.GetLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLocationOperationCompleted);
            }
            this.InvokeAsync("GetLocation", new object[] {
                        ParentId}, this.GetLocationOperationCompleted, userState);
        }
        
        private void OnGetLocationOperationCompleted(object arg) {
            if ((this.GetLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLocationCompleted(this, new GetLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addContact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addContact(int storeId, string tokenKey, string name, string email, string phone, string address, string detail, string clientIp, string captcha) {
            object[] results = this.Invoke("addContact", new object[] {
                        storeId,
                        tokenKey,
                        name,
                        email,
                        phone,
                        address,
                        detail,
                        clientIp,
                        captcha});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addContactAsync(int storeId, string tokenKey, string name, string email, string phone, string address, string detail, string clientIp, string captcha) {
            this.addContactAsync(storeId, tokenKey, name, email, phone, address, detail, clientIp, captcha, null);
        }
        
        /// <remarks/>
        public void addContactAsync(int storeId, string tokenKey, string name, string email, string phone, string address, string detail, string clientIp, string captcha, object userState) {
            if ((this.addContactOperationCompleted == null)) {
                this.addContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddContactOperationCompleted);
            }
            this.InvokeAsync("addContact", new object[] {
                        storeId,
                        tokenKey,
                        name,
                        email,
                        phone,
                        address,
                        detail,
                        clientIp,
                        captcha}, this.addContactOperationCompleted, userState);
        }
        
        private void OnaddContactOperationCompleted(object arg) {
            if ((this.addContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addContactCompleted(this, new addContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchArticle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchArticleResults SearchArticle(int storeId, string tokenKey, int CategoryId, int curentPage, int pageSite, int minPrioty) {
            object[] results = this.Invoke("SearchArticle", new object[] {
                        storeId,
                        tokenKey,
                        CategoryId,
                        curentPage,
                        pageSite,
                        minPrioty});
            return ((SearchArticleResults)(results[0]));
        }
        
        /// <remarks/>
        public void SearchArticleAsync(int storeId, string tokenKey, int CategoryId, int curentPage, int pageSite, int minPrioty) {
            this.SearchArticleAsync(storeId, tokenKey, CategoryId, curentPage, pageSite, minPrioty, null);
        }
        
        /// <remarks/>
        public void SearchArticleAsync(int storeId, string tokenKey, int CategoryId, int curentPage, int pageSite, int minPrioty, object userState) {
            if ((this.SearchArticleOperationCompleted == null)) {
                this.SearchArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchArticleOperationCompleted);
            }
            this.InvokeAsync("SearchArticle", new object[] {
                        storeId,
                        tokenKey,
                        CategoryId,
                        curentPage,
                        pageSite,
                        minPrioty}, this.SearchArticleOperationCompleted, userState);
        }
        
        private void OnSearchArticleOperationCompleted(object arg) {
            if ((this.SearchArticleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchArticleCompleted(this, new SearchArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetArticleById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BlogItem GetArticleById(int storeId, string tokenKey, int id) {
            object[] results = this.Invoke("GetArticleById", new object[] {
                        storeId,
                        tokenKey,
                        id});
            return ((BlogItem)(results[0]));
        }
        
        /// <remarks/>
        public void GetArticleByIdAsync(int storeId, string tokenKey, int id) {
            this.GetArticleByIdAsync(storeId, tokenKey, id, null);
        }
        
        /// <remarks/>
        public void GetArticleByIdAsync(int storeId, string tokenKey, int id, object userState) {
            if ((this.GetArticleByIdOperationCompleted == null)) {
                this.GetArticleByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArticleByIdOperationCompleted);
            }
            this.InvokeAsync("GetArticleById", new object[] {
                        storeId,
                        tokenKey,
                        id}, this.GetArticleByIdOperationCompleted, userState);
        }
        
        private void OnGetArticleByIdOperationCompleted(object arg) {
            if ((this.GetArticleByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArticleByIdCompleted(this, new GetArticleByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddOrder(int st, string tokenKey, string captcha, string name, string email, string phone, string address, string ProductList, int price, int shippingMethod, string modeDetail) {
            object[] results = this.Invoke("AddOrder", new object[] {
                        st,
                        tokenKey,
                        captcha,
                        name,
                        email,
                        phone,
                        address,
                        ProductList,
                        price,
                        shippingMethod,
                        modeDetail});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrderAsync(int st, string tokenKey, string captcha, string name, string email, string phone, string address, string ProductList, int price, int shippingMethod, string modeDetail) {
            this.AddOrderAsync(st, tokenKey, captcha, name, email, phone, address, ProductList, price, shippingMethod, modeDetail, null);
        }
        
        /// <remarks/>
        public void AddOrderAsync(int st, string tokenKey, string captcha, string name, string email, string phone, string address, string ProductList, int price, int shippingMethod, string modeDetail, object userState) {
            if ((this.AddOrderOperationCompleted == null)) {
                this.AddOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrderOperationCompleted);
            }
            this.InvokeAsync("AddOrder", new object[] {
                        st,
                        tokenKey,
                        captcha,
                        name,
                        email,
                        phone,
                        address,
                        ProductList,
                        price,
                        shippingMethod,
                        modeDetail}, this.AddOrderOperationCompleted, userState);
        }
        
        private void OnAddOrderOperationCompleted(object arg) {
            if ((this.AddOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrderCompleted(this, new AddOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRandomAdsSlide", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ads[] GetRandomAdsSlide(int storeId, string tokenKey, string type, int numberOfRecord) {
            object[] results = this.Invoke("GetRandomAdsSlide", new object[] {
                        storeId,
                        tokenKey,
                        type,
                        numberOfRecord});
            return ((Ads[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRandomAdsSlideAsync(int storeId, string tokenKey, string type, int numberOfRecord) {
            this.GetRandomAdsSlideAsync(storeId, tokenKey, type, numberOfRecord, null);
        }
        
        /// <remarks/>
        public void GetRandomAdsSlideAsync(int storeId, string tokenKey, string type, int numberOfRecord, object userState) {
            if ((this.GetRandomAdsSlideOperationCompleted == null)) {
                this.GetRandomAdsSlideOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRandomAdsSlideOperationCompleted);
            }
            this.InvokeAsync("GetRandomAdsSlide", new object[] {
                        storeId,
                        tokenKey,
                        type,
                        numberOfRecord}, this.GetRandomAdsSlideOperationCompleted, userState);
        }
        
        private void OnGetRandomAdsSlideOperationCompleted(object arg) {
            if ((this.GetRandomAdsSlideCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRandomAdsSlideCompleted(this, new GetRandomAdsSlideCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAdsSlide", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ads[] GetAdsSlide(int storeId, string tokenKey, string type) {
            object[] results = this.Invoke("GetAdsSlide", new object[] {
                        storeId,
                        tokenKey,
                        type});
            return ((Ads[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAdsSlideAsync(int storeId, string tokenKey, string type) {
            this.GetAdsSlideAsync(storeId, tokenKey, type, null);
        }
        
        /// <remarks/>
        public void GetAdsSlideAsync(int storeId, string tokenKey, string type, object userState) {
            if ((this.GetAdsSlideOperationCompleted == null)) {
                this.GetAdsSlideOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdsSlideOperationCompleted);
            }
            this.InvokeAsync("GetAdsSlide", new object[] {
                        storeId,
                        tokenKey,
                        type}, this.GetAdsSlideOperationCompleted, userState);
        }
        
        private void OnGetAdsSlideOperationCompleted(object arg) {
            if ((this.GetAdsSlideCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdsSlideCompleted(this, new GetAdsSlideCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCommonConfig", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Webconfig GetCommonConfig(int storeId, string tokenKey) {
            object[] results = this.Invoke("GetCommonConfig", new object[] {
                        storeId,
                        tokenKey});
            return ((Webconfig)(results[0]));
        }
        
        /// <remarks/>
        public void GetCommonConfigAsync(int storeId, string tokenKey) {
            this.GetCommonConfigAsync(storeId, tokenKey, null);
        }
        
        /// <remarks/>
        public void GetCommonConfigAsync(int storeId, string tokenKey, object userState) {
            if ((this.GetCommonConfigOperationCompleted == null)) {
                this.GetCommonConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCommonConfigOperationCompleted);
            }
            this.InvokeAsync("GetCommonConfig", new object[] {
                        storeId,
                        tokenKey}, this.GetCommonConfigOperationCompleted, userState);
        }
        
        private void OnGetCommonConfigOperationCompleted(object arg) {
            if ((this.GetCommonConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCommonConfigCompleted(this, new GetCommonConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBlogCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BlogCategory[] GetBlogCategory(int storeId, string tokenKey) {
            object[] results = this.Invoke("GetBlogCategory", new object[] {
                        storeId,
                        tokenKey});
            return ((BlogCategory[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBlogCategoryAsync(int storeId, string tokenKey) {
            this.GetBlogCategoryAsync(storeId, tokenKey, null);
        }
        
        /// <remarks/>
        public void GetBlogCategoryAsync(int storeId, string tokenKey, object userState) {
            if ((this.GetBlogCategoryOperationCompleted == null)) {
                this.GetBlogCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBlogCategoryOperationCompleted);
            }
            this.InvokeAsync("GetBlogCategory", new object[] {
                        storeId,
                        tokenKey}, this.GetBlogCategoryOperationCompleted, userState);
        }
        
        private void OnGetBlogCategoryOperationCompleted(object arg) {
            if ((this.GetBlogCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBlogCategoryCompleted(this, new GetBlogCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResult SearchProduct(int storeId, string tokenKey, string CategoryId, string parentCategoryId, string originId, int priceFrom, int priceTo, int curentPage, int pageSite, string keyWord, string order, int minPrioty) {
            object[] results = this.Invoke("SearchProduct", new object[] {
                        storeId,
                        tokenKey,
                        CategoryId,
                        parentCategoryId,
                        originId,
                        priceFrom,
                        priceTo,
                        curentPage,
                        pageSite,
                        keyWord,
                        order,
                        minPrioty});
            return ((SearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void SearchProductAsync(int storeId, string tokenKey, string CategoryId, string parentCategoryId, string originId, int priceFrom, int priceTo, int curentPage, int pageSite, string keyWord, string order, int minPrioty) {
            this.SearchProductAsync(storeId, tokenKey, CategoryId, parentCategoryId, originId, priceFrom, priceTo, curentPage, pageSite, keyWord, order, minPrioty, null);
        }
        
        /// <remarks/>
        public void SearchProductAsync(int storeId, string tokenKey, string CategoryId, string parentCategoryId, string originId, int priceFrom, int priceTo, int curentPage, int pageSite, string keyWord, string order, int minPrioty, object userState) {
            if ((this.SearchProductOperationCompleted == null)) {
                this.SearchProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchProductOperationCompleted);
            }
            this.InvokeAsync("SearchProduct", new object[] {
                        storeId,
                        tokenKey,
                        CategoryId,
                        parentCategoryId,
                        originId,
                        priceFrom,
                        priceTo,
                        curentPage,
                        pageSite,
                        keyWord,
                        order,
                        minPrioty}, this.SearchProductOperationCompleted, userState);
        }
        
        private void OnSearchProductOperationCompleted(object arg) {
            if ((this.SearchProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchProductCompleted(this, new SearchProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductByParentCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResult GetProductByParentCategory(int storeId, string tokenKey, int parentCategoryId, int curentPage, int pageSite, int minPrioty) {
            object[] results = this.Invoke("GetProductByParentCategory", new object[] {
                        storeId,
                        tokenKey,
                        parentCategoryId,
                        curentPage,
                        pageSite,
                        minPrioty});
            return ((SearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductByParentCategoryAsync(int storeId, string tokenKey, int parentCategoryId, int curentPage, int pageSite, int minPrioty) {
            this.GetProductByParentCategoryAsync(storeId, tokenKey, parentCategoryId, curentPage, pageSite, minPrioty, null);
        }
        
        /// <remarks/>
        public void GetProductByParentCategoryAsync(int storeId, string tokenKey, int parentCategoryId, int curentPage, int pageSite, int minPrioty, object userState) {
            if ((this.GetProductByParentCategoryOperationCompleted == null)) {
                this.GetProductByParentCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductByParentCategoryOperationCompleted);
            }
            this.InvokeAsync("GetProductByParentCategory", new object[] {
                        storeId,
                        tokenKey,
                        parentCategoryId,
                        curentPage,
                        pageSite,
                        minPrioty}, this.GetProductByParentCategoryOperationCompleted, userState);
        }
        
        private void OnGetProductByParentCategoryOperationCompleted(object arg) {
            if ((this.GetProductByParentCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductByParentCategoryCompleted(this, new GetProductByParentCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductByCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResult GetProductByCategory(int storeId, string tokenKey, int CategoryId, int curentPage, int pageSite, int minPrioty) {
            object[] results = this.Invoke("GetProductByCategory", new object[] {
                        storeId,
                        tokenKey,
                        CategoryId,
                        curentPage,
                        pageSite,
                        minPrioty});
            return ((SearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductByCategoryAsync(int storeId, string tokenKey, int CategoryId, int curentPage, int pageSite, int minPrioty) {
            this.GetProductByCategoryAsync(storeId, tokenKey, CategoryId, curentPage, pageSite, minPrioty, null);
        }
        
        /// <remarks/>
        public void GetProductByCategoryAsync(int storeId, string tokenKey, int CategoryId, int curentPage, int pageSite, int minPrioty, object userState) {
            if ((this.GetProductByCategoryOperationCompleted == null)) {
                this.GetProductByCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductByCategoryOperationCompleted);
            }
            this.InvokeAsync("GetProductByCategory", new object[] {
                        storeId,
                        tokenKey,
                        CategoryId,
                        curentPage,
                        pageSite,
                        minPrioty}, this.GetProductByCategoryOperationCompleted, userState);
        }
        
        private void OnGetProductByCategoryOperationCompleted(object arg) {
            if ((this.GetProductByCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductByCategoryCompleted(this, new GetProductByCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSaleProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductItem[] GetSaleProduct(int storeId, string tokenKey) {
            object[] results = this.Invoke("GetSaleProduct", new object[] {
                        storeId,
                        tokenKey});
            return ((ProductItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSaleProductAsync(int storeId, string tokenKey) {
            this.GetSaleProductAsync(storeId, tokenKey, null);
        }
        
        /// <remarks/>
        public void GetSaleProductAsync(int storeId, string tokenKey, object userState) {
            if ((this.GetSaleProductOperationCompleted == null)) {
                this.GetSaleProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSaleProductOperationCompleted);
            }
            this.InvokeAsync("GetSaleProduct", new object[] {
                        storeId,
                        tokenKey}, this.GetSaleProductOperationCompleted, userState);
        }
        
        private void OnGetSaleProductOperationCompleted(object arg) {
            if ((this.GetSaleProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSaleProductCompleted(this, new GetSaleProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductItem GetProductDetail(int storeId, string tokenKey, int id) {
            object[] results = this.Invoke("GetProductDetail", new object[] {
                        storeId,
                        tokenKey,
                        id});
            return ((ProductItem)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductDetailAsync(int storeId, string tokenKey, int id) {
            this.GetProductDetailAsync(storeId, tokenKey, id, null);
        }
        
        /// <remarks/>
        public void GetProductDetailAsync(int storeId, string tokenKey, int id, object userState) {
            if ((this.GetProductDetailOperationCompleted == null)) {
                this.GetProductDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductDetailOperationCompleted);
            }
            this.InvokeAsync("GetProductDetail", new object[] {
                        storeId,
                        tokenKey,
                        id}, this.GetProductDetailOperationCompleted, userState);
        }
        
        private void OnGetProductDetailOperationCompleted(object arg) {
            if ((this.GetProductDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductDetailCompleted(this, new GetProductDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Location {
        
        private int idField;
        
        private string nameField;
        
        private int parentIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductItem {
        
        private int originIDField;
        
        private string catNameField;
        
        private int parentIdField;
        
        private decimal salePriceField;
        
        private decimal priceField;
        
        private string updateTimeField;
        
        private string originNameField;
        
        private string imagesField;
        
        private string detailField;
        
        private string prNameField;
        
        private int catIDField;
        
        private string parentCatNameField;
        
        private int warrantyField;
        
        private int idField;
        
        private bool isSaleField;
        
        private int rankField;
        
        private string shortDescField;
        
        private string saleEndTimeField;
        
        private string scriptField;
        
        private string keyWordField;
        
        private bool isInstockField;
        
        private string[] imagesSlideField;
        
        /// <remarks/>
        public int OriginID {
            get {
                return this.originIDField;
            }
            set {
                this.originIDField = value;
            }
        }
        
        /// <remarks/>
        public string CatName {
            get {
                return this.catNameField;
            }
            set {
                this.catNameField = value;
            }
        }
        
        /// <remarks/>
        public int ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal SalePrice {
            get {
                return this.salePriceField;
            }
            set {
                this.salePriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string OriginName {
            get {
                return this.originNameField;
            }
            set {
                this.originNameField = value;
            }
        }
        
        /// <remarks/>
        public string Images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
        
        /// <remarks/>
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        public string PrName {
            get {
                return this.prNameField;
            }
            set {
                this.prNameField = value;
            }
        }
        
        /// <remarks/>
        public int CatID {
            get {
                return this.catIDField;
            }
            set {
                this.catIDField = value;
            }
        }
        
        /// <remarks/>
        public string ParentCatName {
            get {
                return this.parentCatNameField;
            }
            set {
                this.parentCatNameField = value;
            }
        }
        
        /// <remarks/>
        public int Warranty {
            get {
                return this.warrantyField;
            }
            set {
                this.warrantyField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSale {
            get {
                return this.isSaleField;
            }
            set {
                this.isSaleField = value;
            }
        }
        
        /// <remarks/>
        public int Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        public string ShortDesc {
            get {
                return this.shortDescField;
            }
            set {
                this.shortDescField = value;
            }
        }
        
        /// <remarks/>
        public string SaleEndTime {
            get {
                return this.saleEndTimeField;
            }
            set {
                this.saleEndTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }
        
        /// <remarks/>
        public string KeyWord {
            get {
                return this.keyWordField;
            }
            set {
                this.keyWordField = value;
            }
        }
        
        /// <remarks/>
        public bool IsInstock {
            get {
                return this.isInstockField;
            }
            set {
                this.isInstockField = value;
            }
        }
        
        /// <remarks/>
        public string[] ImagesSlide {
            get {
                return this.imagesSlideField;
            }
            set {
                this.imagesSlideField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResult {
        
        private ProductItem[] itemField;
        
        private int resultCountField;
        
        /// <remarks/>
        public ProductItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public int ResultCount {
            get {
                return this.resultCountField;
            }
            set {
                this.resultCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BlogCategory {
        
        private int idField;
        
        private string nameField;
        
        private string thumbField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Thumb {
            get {
                return this.thumbField;
            }
            set {
                this.thumbField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductCategory {
        
        private string nameField;
        
        private int idField;
        
        private ProductCategory[] childCategoryField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public ProductCategory[] ChildCategory {
            get {
                return this.childCategoryField;
            }
            set {
                this.childCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Menu {
        
        private Menu[] chidMenuField;
        
        private int idField;
        
        private string linkField;
        
        private int parentIdField;
        
        private int priotyField;
        
        private string tittleField;
        
        /// <remarks/>
        public Menu[] ChidMenu {
            get {
                return this.chidMenuField;
            }
            set {
                this.chidMenuField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public int ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        public int Prioty {
            get {
                return this.priotyField;
            }
            set {
                this.priotyField = value;
            }
        }
        
        /// <remarks/>
        public string Tittle {
            get {
                return this.tittleField;
            }
            set {
                this.tittleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Webconfig {
        
        private Menu[] menuListField;
        
        private string faceBookLinkField;
        
        private string skypeField;
        
        private string hotLineField;
        
        private string pageScriptField;
        
        private string footerField;
        
        private string logoField;
        
        private string descField;
        
        private ProductCategory[] productCategoryListField;
        
        private string emailField;
        
        private string addressField;
        
        private string anperoPluginField;
        
        private string nameField;
        
        private int themeOptionField;
        
        /// <remarks/>
        public Menu[] MenuList {
            get {
                return this.menuListField;
            }
            set {
                this.menuListField = value;
            }
        }
        
        /// <remarks/>
        public string FaceBookLink {
            get {
                return this.faceBookLinkField;
            }
            set {
                this.faceBookLinkField = value;
            }
        }
        
        /// <remarks/>
        public string Skype {
            get {
                return this.skypeField;
            }
            set {
                this.skypeField = value;
            }
        }
        
        /// <remarks/>
        public string HotLine {
            get {
                return this.hotLineField;
            }
            set {
                this.hotLineField = value;
            }
        }
        
        /// <remarks/>
        public string PageScript {
            get {
                return this.pageScriptField;
            }
            set {
                this.pageScriptField = value;
            }
        }
        
        /// <remarks/>
        public string Footer {
            get {
                return this.footerField;
            }
            set {
                this.footerField = value;
            }
        }
        
        /// <remarks/>
        public string Logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public ProductCategory[] ProductCategoryList {
            get {
                return this.productCategoryListField;
            }
            set {
                this.productCategoryListField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string AnperoPlugin {
            get {
                return this.anperoPluginField;
            }
            set {
                this.anperoPluginField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int ThemeOption {
            get {
                return this.themeOptionField;
            }
            set {
                this.themeOptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ads {
        
        private string clickUrlField;
        
        private string descriptionField;
        
        private string imagesUrlField;
        
        /// <remarks/>
        public string ClickUrl {
            get {
                return this.clickUrlField;
            }
            set {
                this.clickUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ImagesUrl {
            get {
                return this.imagesUrlField;
            }
            set {
                this.imagesUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BlogItem {
        
        private int idField;
        
        private string titleField;
        
        private string createDateField;
        
        private string shotDescField;
        
        private string thumbField;
        
        private string tagField;
        
        private string tagKhongDauField;
        
        private int viewTimeField;
        
        private string contentField;
        
        private int categoryIdField;
        
        private string categoryNameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public string ShotDesc {
            get {
                return this.shotDescField;
            }
            set {
                this.shotDescField = value;
            }
        }
        
        /// <remarks/>
        public string Thumb {
            get {
                return this.thumbField;
            }
            set {
                this.thumbField = value;
            }
        }
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        public string TagKhongDau {
            get {
                return this.tagKhongDauField;
            }
            set {
                this.tagKhongDauField = value;
            }
        }
        
        /// <remarks/>
        public int ViewTime {
            get {
                return this.viewTimeField;
            }
            set {
                this.viewTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchArticleResults {
        
        private BlogItem[] itemListField;
        
        private int resultsCountField;
        
        /// <remarks/>
        public BlogItem[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
            }
        }
        
        /// <remarks/>
        public int ResultsCount {
            get {
                return this.resultsCountField;
            }
            set {
                this.resultsCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetLocationCompletedEventHandler(object sender, GetLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Location[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Location[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void addContactCompletedEventHandler(object sender, addContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SearchArticleCompletedEventHandler(object sender, SearchArticleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchArticleResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchArticleResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetArticleByIdCompletedEventHandler(object sender, GetArticleByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArticleByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArticleByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlogItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlogItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AddOrderCompletedEventHandler(object sender, AddOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetRandomAdsSlideCompletedEventHandler(object sender, GetRandomAdsSlideCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRandomAdsSlideCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRandomAdsSlideCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ads[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ads[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetAdsSlideCompletedEventHandler(object sender, GetAdsSlideCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdsSlideCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdsSlideCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ads[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ads[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetCommonConfigCompletedEventHandler(object sender, GetCommonConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCommonConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCommonConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Webconfig Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Webconfig)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetBlogCategoryCompletedEventHandler(object sender, GetBlogCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBlogCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBlogCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlogCategory[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlogCategory[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SearchProductCompletedEventHandler(object sender, SearchProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetProductByParentCategoryCompletedEventHandler(object sender, GetProductByParentCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductByParentCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductByParentCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetProductByCategoryCompletedEventHandler(object sender, GetProductByCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductByCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductByCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetSaleProductCompletedEventHandler(object sender, GetSaleProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSaleProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSaleProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetProductDetailCompletedEventHandler(object sender, GetProductDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductItem)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591